# NumPy Basics

NumPy (Numerical Python) is a Python library used for numerical computing.

It provides:

- Fast array operations
- Mathematical functions
- Statistical computations
- Linear algebra support
- Foundation for Pandas, Scikit-Learn, and many ML libraries

## Why NumPy?

Python lists are flexible but inefficient for large-scale numerical computation.

NumPy solves this problem by:

1. Storing data efficiently in memory
2. Performing operations using optimized C code
3. Supporting vectorized operations
4. Providing powerful mathematical functions

NumPy is the foundation of the modern Python Data Analytics ecosystem.

In [ ]:
import numpy as np

# Python Lists vs NumPy Arrays

Both can store collections of values.

Example:

Python List:
[1, 2, 3, 4]

NumPy Array:
array([1, 2, 3, 4])

Although they look similar, they are implemented differently.

## Python List

- Stores references to objects
- Can contain mixed data types
- Slower for numerical computation
- More memory usage

## NumPy Array

- Stores homogeneous data
- Faster computation
- Less memory usage
- Supports vectorized operations

NumPy arrays are designed specifically for numerical data.

In [ ]:
import numpy as np
numbers_list = [1, 2, 3, 4]

numbers_array = np.array([1, 2, 3, 4])

print(numbers_list)
print(numbers_array)

## Multiplication Example

A common beginner mistake is assuming lists and arrays behave the same way.

List multiplication repeats the list.

Array multiplication performs mathematical multiplication.

In [ ]:
import numpy as np
numbers_list = [1, 2, 3]

numbers_array = np.array([1, 2, 3])

print("List Result:")
print(numbers_list * 2)

print("\nArray Result:")
print(numbers_array * 2)

## Vectorization

Vectorization means applying an operation to an entire array without writing loops.

This is one of the biggest reasons NumPy is fast.

Without NumPy:

- Explicit loops are required.

With NumPy:

- Operations happen on entire arrays.

In [ ]:
import numpy as np
prices = np.array([100, 200, 300, 400])

taxed_prices = prices * 1.18

print(taxed_prices)

# Creating Arrays

Arrays can be created from:

- Lists
- Tuples
- Existing arrays
- Built-in NumPy functions

The most common method is using np.array().

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr1)
print(arr2)

## Dimensions

1D Array

[1, 2, 3]

2D Array

[
 [1, 2, 3],
 [4, 5, 6]
]

3D Array

Collection of multiple 2D arrays.

Think:

1D → Line

2D → Table

3D → Stack of Tables

In [ ]:
one_d = np.array([1, 2, 3])

two_d = np.array([
    [1, 2],
    [3, 4]
])

three_d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("1D ARRAY:",one_d)
print("2D ARRAY:",two_d)
print("3D ARRAY:",three_d)

# Core Properties of NumPy Arrays

## Homogeneous

All elements are stored using the same data type.

## Fixed Size

Size is defined when the array is created.

## Fast Operations

Operations are performed using optimized internal implementations.

## Memory Efficient

Uses contiguous memory allocation.

## Automatic Type Conversion

NumPy automatically converts values to a common compatible datatype.

This process is called Upcasting.

In [ ]:
A=[1,'A','APPLE',1.8]
arr = np.array(A)

print(arr,arr.dtype)

arr = np.array([1, 2, 3.5])  

print(arr)
print(arr.dtype)


# Array Attributes

These attributes help us understand the structure of an array.

Important for debugging datasets.

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Datatype:", arr.dtype)
print("Item Size:", arr.itemsize)

## Attribute Meanings

ndim
→ Number of dimensions

shape
→ Structure of array

size
→ Total elements

dtype
→ Datatype

itemsize
→ Bytes occupied by each element

### Important Tip

Whenever something looks wrong:

Check:

- shape
- dtype

These two solve most beginner errors.

# Array Initialization Functions

NumPy provides helper functions to quickly create arrays.

These are frequently used while testing code and building examples.

In [ ]:
print(np.zeros((3, 3)))   #null matrix

print()

print(np.ones((2, 2)))   

print()

print(np.full((2, 2), 99))   # Creates an array filled with a specific value.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[99 99]
 [99 99]]


### Changing Datatype

By default zeros(), ones() creates float values.

We can specify datatype manually.

In [34]:
arr = np.zeros((2,3),dtype=int)
print(arr)
print()
print(np.ones((2, 2),dtype=int))
print()

[[0 0 0]
 [0 0 0]]

[[1 1]
 [1 1]]



In [35]:
print(np.identity(4))   # identity matrix 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## np.arange()

Similar to Python range().

Generates evenly spaced values.

Syntax:

np.arange(start, stop, step)

Important:

Stop value is excluded.

In [36]:
arr = np.arange(1,10,2)

print(arr)

[1 3 5 7 9]


## np.linspace()

Creates evenly spaced values between two numbers.

Syntax:

np.linspace(start, stop, number_of_values)

Important:

Stop value is INCLUDED.

In [ ]:
arr = np.linspace( 1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


### Difference Between arange() and linspace()

arange()

- Uses step size
- Stop value excluded

linspace()

- Uses number of values
- Stop value included

In [38]:
print(np.arange(1,10,3))
print()

print(np.linspace(1,10,3))

[1 4 7]

[ 1.   5.5 10. ]


## np.logspace()

Creates logarithmically spaced values.

Instead of increasing linearly,
values increase exponentially.

Useful in:

- Signal Processing
- Scientific Computing
- Machine Learning Experiments

### Understanding logspace()

logspace(1,3,5)

means:

10¹ to 10³

not

1 to 3

In [39]:
arr = np.logspace(1,3,5)
print(arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


## np.eye()

Creates an identity matrix.

Diagonal values = 1

Remaining values = 0

In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.random.rand(3, 3))    #takes random values from float(0 to 1)

In [41]:
print(np.random.randn(2,3))   # random floats from standard normal distribution

[[-1.28203216 -1.06160391  0.69394519]
 [-0.65227003  0.14979665  0.74771432]]


In [ ]:
print(                             # taking random values from a specified range
    np.random.randint(1,10,size=(3, 3))
    )

[[9 1 6]
 [2 1 9]
 [9 3 8]]
